var h1;
var canvas;
var x = 100;
var y = 100;
var counter = 0;



function setup() {
  canvas = createCanvas(300,300);
  canvas.position(window.innerWidth/2,window.innerHeight/2);
  
  par    = createP("this is a paragraph element generated from the sketch.js file")
  par.position(window.innerWidth/5,window.innerHeight/2);
  
  h1     = createElement('h1', 'STANDBY');
  h1.position(window.innerWidth*.7, window.innerHeight*.01);
  
  createDiv("sup");
}

function mousePressed(){
  //createP(random(1000)+" generated by createP at mousePress");
  
  par.html(random(10000));
  par.position(random(window.innerWidth),random(window.innerHeight));
  
  if (counter % 2 == 0){
      h1.html('STANDBY');
  } else {
      h1.html('as you were');
  }
  counter ++;
  
  
  
  
}


function draw() {
  //clear();
  background(150);
  fill(255,0,0);
  rect(x, y,50,50);
  h1.position(x*(window.innerWidth/200),y*(window.innerHeight/200));
  x = x + random(-5,5);
  y = y + random(-5,5);
  x = constrain(x, 0, width*.8);
  y = constrain(y, 0, height*.8);
  
}